using System.Collections.ObjectModel;

namespace ScribbleHubFeed;

public enum Tag
{
    
}

public static class Tags
{
    public static Tag Parse(string s)
    {
        return TagMap[s];
    }
    
    public static Tag? TryParse(string s)
    {
        if (TagMap.TryGetValue(s, out var tag))
        {
            return tag;
        }
        else
        {
            return null;
        }
    }
    
    public static IReadOnlyDictionary<string, Tag> TagMap { get; } = new ReadOnlyDictionary<string, Tag>(new Dictionary<string, Tag>()
    {
        { "Abandoned Children", (Tag)119 },
        { "Ability Steal", (Tag)120 },
        { "Absent Parents", (Tag)121 },
        { "Abusive Characters", (Tag)122 },
        { "Academy", (Tag)123 },
        { "Accelerated Growth", (Tag)124 },
        { "Acting", (Tag)125 },
        { "Adopted Children", (Tag)137 },
        { "Adopted Protagonist", (Tag)138 },
        { "Adultery", (Tag)139 },
        { "Adventurers", (Tag)140 },
        { "Affair", (Tag)141 },
        { "Age Progression", (Tag)142 },
        { "Age Regression", (Tag)143 },
        { "Aggressive Characters", (Tag)144 },
        { "Alchemy", (Tag)145 },
        { "Aliens", (Tag)146 },
        { "All-Girls School", (Tag)147 },
        { "Alternate World", (Tag)148 },
        { "Amnesia", (Tag)149 },
        { "Amusement Park", (Tag)150 },
        { "Ancient China", (Tag)152 },
        { "Ancient Times", (Tag)153 },
        { "Androgynous Characters", (Tag)154 },
        { "Androids", (Tag)155 },
        { "Angels", (Tag)156 },
        { "Animal Characteristics", (Tag)157 },
        { "Animal Rearing", (Tag)158 },
        { "Anti-Magic", (Tag)159 },
        { "Anti-social Protagonist", (Tag)160 },
        { "Antihero Protagonist", (Tag)161 },
        { "Antique Shop", (Tag)162 },
        { "Apartment Life", (Tag)163 },
        { "Apathetic Protagonist", (Tag)164 },
        { "Apocalypse", (Tag)165 },
        { "Appearance Changes", (Tag)166 },
        { "Appearance Different from Actual Age", (Tag)167 },
        { "Archery", (Tag)168 },
        { "Aristocracy", (Tag)169 },
        { "Arms Dealers", (Tag)170 },
        { "Army", (Tag)171 },
        { "Army Building", (Tag)172 },
        { "Arranged Marriage", (Tag)173 },
        { "Arrogant Characters", (Tag)174 },
        { "Artifact Crafting", (Tag)175 },
        { "Artifacts", (Tag)176 },
        { "Artificial Intelligence", (Tag)177 },
        { "Artists", (Tag)178 },
        { "Assassins", (Tag)179 },
        { "Astrologers", (Tag)180 },
        { "Autism", (Tag)181 },
        { "Automatons", (Tag)182 },
        { "Average-looking Protagonist", (Tag)183 },
        { "Awkward Protagonist", (Tag)185 },
        { "Bands", (Tag)186 },
        { "Based on a Movie", (Tag)187 },
        { "Based on a Song", (Tag)188 },
        { "Based on a Video Game", (Tag)190 },
        { "Based on a Visual Novel", (Tag)191 },
        { "Based on an Anime", (Tag)192 },
        { "Battle Academy", (Tag)193 },
        { "Battle Competition", (Tag)194 },
        { "BDSM", (Tag)195 },
        { "Beast Companions", (Tag)196 },
        { "Beastkin", (Tag)197 },
        { "Beasts", (Tag)198 },
        { "Beautiful Couple", (Tag)199 },
        { "Beautiful Female Lead", (Tag)200 },
        { "Betrayal", (Tag)202 },
        { "Bickering Couple", (Tag)203 },
        { "Biochip", (Tag)204 },
        { "Biography", (Tag)205 },
        { "Bisexual Protagonist", (Tag)206 },
        { "Black Belly", (Tag)207 },
        { "Blackmail", (Tag)208 },
        { "Blacksmith", (Tag)209 },
        { "Blind Dates", (Tag)210 },
        { "Blind Protagonist", (Tag)211 },
        { "Blood Manipulation", (Tag)212 },
        { "Bloodlines", (Tag)213 },
        { "Body Swap", (Tag)214 },
        { "Body Tempering", (Tag)215 },
        { "Body-double", (Tag)216 },
        { "Bodyguards", (Tag)217 },
        { "Books", (Tag)218 },
        { "Bookworm", (Tag)219 },
        { "Boss-Subordinate Relationship", (Tag)220 },
        { "Boy's Love Subplot", (Tag)760 },
        { "Brainwashing", (Tag)221 },
        { "Broken Engagement", (Tag)223 },
        { "Brother Complex", (Tag)224 },
        { "Brotherhood", (Tag)225 },
        { "Buddhism", (Tag)226 },
        { "Bullying", (Tag)227 },
        { "Business Management", (Tag)228 },
        { "Businessmen", (Tag)229 },
        { "Butlers", (Tag)230 },
        { "Calm Protagonist", (Tag)231 },
        { "Cannibalism", (Tag)232 },
        { "Card Games", (Tag)233 },
        { "Carefree Protagonist", (Tag)234 },
        { "Caring Protagonist", (Tag)235 },
        { "Cautious Protagonist", (Tag)236 },
        { "Celebrities", (Tag)237 },
        { "Character Growth", (Tag)238 },
        { "Charismatic Protagonist", (Tag)239 },
        { "Charming Protagonist", (Tag)240 },
        { "Chat Rooms", (Tag)241 },
        { "Cheating", (Tag)20892 },
        { "Cheats", (Tag)242 },
        { "Chefs", (Tag)243 },
        { "Child Abuse", (Tag)244 },
        { "Child Protagonist", (Tag)245 },
        { "Childcare", (Tag)246 },
        { "Childhood Friends", (Tag)247 },
        { "Childhood Love", (Tag)248 },
        { "Childhood Promise", (Tag)249 },
        { "Childish Protagonist", (Tag)250 },
        { "Chuunibyou", (Tag)251 },
        { "Clan Building", (Tag)252 },
        { "Classic", (Tag)253 },
        { "Clever Protagonist", (Tag)254 },
        { "Clingy Lover", (Tag)255 },
        { "Clones", (Tag)256 },
        { "Clubs", (Tag)257 },
        { "Clumsy Love Interests", (Tag)258 },
        { "Co-Workers", (Tag)259 },
        { "Cohabitation", (Tag)260 },
        { "Cold Love Interests", (Tag)261 },
        { "Cold Protagonist", (Tag)262 },
        { "Collection of Short Stories", (Tag)263 },
        { "College/University", (Tag)264 },
        { "Coma", (Tag)265 },
        { "Comedic Undertone", (Tag)266 },
        { "Coming of Age", (Tag)267 },
        { "Complex Family Relationships", (Tag)268 },
        { "Conditional Power", (Tag)269 },
        { "Confident Protagonist", (Tag)270 },
        { "Confinement", (Tag)271 },
        { "Conflicting Loyalties", (Tag)272 },
        { "Conspiracies", (Tag)273 },
        { "Contracts", (Tag)274 },
        { "Cooking", (Tag)275 },
        { "Corruption", (Tag)276 },
        { "Cosmic Wars", (Tag)277 },
        { "Cosplay", (Tag)278 },
        { "Couple Growth", (Tag)279 },
        { "Court Official", (Tag)280 },
        { "Cousins", (Tag)281 },
        { "Cowardly Protagonist", (Tag)282 },
        { "Crafting", (Tag)283 },
        { "Crazy Protagonist", (Tag)1534 },
        { "Crime", (Tag)284 },
        { "Criminals", (Tag)285 },
        { "Cross-dressing", (Tag)286 },
        { "Crossover", (Tag)287 },
        { "Cruel Characters", (Tag)288 },
        { "Cryostasis", (Tag)289 },
        { "Cultivation", (Tag)290 },
        { "Cunning Protagonist", (Tag)292 },
        { "Curious Protagonist", (Tag)293 },
        { "Curses", (Tag)294 },
        { "Cute Children", (Tag)295 },
        { "Cute Protagonist", (Tag)296 },
        { "Cute Story", (Tag)297 },
        { "Cyberpunk", (Tag)960 },
        { "Dancers", (Tag)298 },
        { "Dao Companion", (Tag)299 },
        { "Dao Comprehension", (Tag)300 },
        { "Daoism", (Tag)301 },
        { "Dark", (Tag)302 },
        { "Dead Protagonist", (Tag)303 },
        { "Death", (Tag)304 },
        { "Death of Loved Ones", (Tag)305 },
        { "Debts", (Tag)306 },
        { "Delinquents", (Tag)307 },
        { "Delusions", (Tag)308 },
        { "Demi-Humans", (Tag)309 },
        { "Demon Lord", (Tag)310 },
        { "Demonic Cultivation Technique", (Tag)311 },
        { "Demons", (Tag)312 },
        { "Dense Protagonist", (Tag)313 },
        { "Depictions of Cruelty", (Tag)314 },
        { "Depression", (Tag)315 },
        { "Destiny", (Tag)316 },
        { "Detectives", (Tag)317 },
        { "Determined Protagonist", (Tag)318 },
        { "Devoted Love Interests", (Tag)319 },
        { "Different Social Status", (Tag)320 },
        { "Disabilities", (Tag)321 },
        { "Discrimination", (Tag)322 },
        { "Disfigurement", (Tag)323 },
        { "Dishonest Protagonist", (Tag)324 },
        { "Distrustful Protagonist", (Tag)325 },
        { "Divination", (Tag)326 },
        { "Divine Protection", (Tag)327 },
        { "Divorce", (Tag)328 },
        { "Doctors", (Tag)329 },
        { "Dolls/Puppets", (Tag)330 },
        { "Domestic Affairs", (Tag)331 },
        { "Doting Love Interests", (Tag)332 },
        { "Doting Older Siblings", (Tag)333 },
        { "Doting Parents", (Tag)334 },
        { "Dragon Riders", (Tag)335 },
        { "Dragon Slayers", (Tag)336 },
        { "Dragons", (Tag)337 },
        { "Dreams", (Tag)338 },
        { "Drugs", (Tag)339 },
        { "Druids", (Tag)340 },
        { "Dungeon Master", (Tag)341 },
        { "Dungeons", (Tag)342 },
        { "Dwarfs", (Tag)343 },
        { "Dystopia", (Tag)344 },
        { "e-Sports", (Tag)345 },
        { "Early Romance", (Tag)346 },
        { "Earth Invasion", (Tag)347 },
        { "Easy Going Life", (Tag)348 },
        { "Economics", (Tag)349 },
        { "Editors", (Tag)350 },
        { "Eidetic Memory", (Tag)351 },
        { "Elderly Protagonist", (Tag)352 },
        { "Elemental Magic", (Tag)353 },
        { "Elves", (Tag)354 },
        { "Emotionally Weak Protagonist", (Tag)355 },
        { "Empires", (Tag)356 },
        { "Enemies Become Allies", (Tag)357 },
        { "Enemies Become Lovers", (Tag)358 },
        { "Engagement", (Tag)359 },
        { "Engineer", (Tag)360 },
        { "Enlightenment", (Tag)361 },
        { "Episodic", (Tag)362 },
        { "Eunuch", (Tag)363 },
        { "European Ambience", (Tag)364 },
        { "Evil Gods", (Tag)365 },
        { "Evil Organizations", (Tag)366 },
        { "Evil Protagonist", (Tag)367 },
        { "Evil Religions", (Tag)368 },
        { "Evolution", (Tag)369 },
        { "Exhibitionism", (Tag)370 },
        { "Exorcism", (Tag)371 },
        { "Eye Powers", (Tag)372 },
        { "Fairies", (Tag)373 },
        { "Fallen Angels", (Tag)374 },
        { "Fallen Nobility", (Tag)375 },
        { "Familial Love", (Tag)376 },
        { "Familiars", (Tag)377 },
        { "Family", (Tag)378 },
        { "Family Business", (Tag)379 },
        { "Family Conflict", (Tag)380 },
        { "Famous Parents", (Tag)381 },
        { "Famous Protagonist", (Tag)382 },
        { "Fanaticism", (Tag)383 },
        { "Fantasy Creatures", (Tag)385 },
        { "Fantasy World", (Tag)386 },
        { "Farming", (Tag)387 },
        { "Fast Cultivation", (Tag)388 },
        { "Fast Learner", (Tag)389 },
        { "Fat Protagonist", (Tag)390 },
        { "Fat to Fit", (Tag)391 },
        { "Fated Lovers", (Tag)392 },
        { "Fearless Protagonist", (Tag)393 },
        { "Female Master", (Tag)395 },
        { "Female Protagonist", (Tag)396 },
        { "Female to Male", (Tag)397 },
        { "Feng Shui", (Tag)398 },
        { "Firearms", (Tag)399 },
        { "First Love", (Tag)400 },
        { "First-time Intercourse", (Tag)401 },
        { "Flashbacks", (Tag)402 },
        { "Fleet Battles", (Tag)403 },
        { "Folklore", (Tag)404 },
        { "Forced into a Relationship", (Tag)405 },
        { "Forced Living Arrangements", (Tag)406 },
        { "Forced Marriage", (Tag)407 },
        { "Forgetful Protagonist", (Tag)408 },
        { "Former Hero", (Tag)409 },
        { "Fourth Wall", (Tag)1150 },
        { "Fox Spirits", (Tag)410 },
        { "Friends Become Enemies", (Tag)411 },
        { "Friendship", (Tag)412 },
        { "Fujoshi", (Tag)413 },
        { "Futanari", (Tag)414 },
        { "Futuristic Setting", (Tag)415 },
        { "Galge", (Tag)416 },
        { "Gambling", (Tag)417 },
        { "Game Elements", (Tag)418 },
        { "Game Ranking System", (Tag)419 },
        { "Gamers", (Tag)420 },
        { "Gangs", (Tag)421 },
        { "Gate to Another World", (Tag)422 },
        { "Genderless Protagonist", (Tag)423 },
        { "Generals", (Tag)424 },
        { "Genetic Modifications", (Tag)425 },
        { "Genies", (Tag)426 },
        { "Genius Protagonist", (Tag)427 },
        { "Ghosts", (Tag)428 },
        { "Girl's Love Subplot", (Tag)759 },
        { "Gladiators", (Tag)429 },
        { "Glasses-wearing Love Interests", (Tag)430 },
        { "Glasses-wearing Protagonist", (Tag)431 },
        { "Goblins", (Tag)432 },
        { "God Protagonist", (Tag)433 },
        { "God-human Relationship", (Tag)434 },
        { "Goddesses", (Tag)435 },
        { "Godly Powers", (Tag)436 },
        { "Gods", (Tag)437 },
        { "Golems", (Tag)438 },
        { "Gore", (Tag)439 },
        { "Grave Keepers", (Tag)440 },
        { "Grinding", (Tag)441 },
        { "Guardian Relationship", (Tag)442 },
        { "Guilds", (Tag)443 },
        { "Gunfighters", (Tag)444 },
        { "Hackers", (Tag)445 },
        { "Half-human Protagonist", (Tag)446 },
        { "Handjob", (Tag)447 },
        { "Handsome Male Lead", (Tag)448 },
        { "Hard-Working Protagonist", (Tag)449 },
        { "Harem-seeking Protagonist", (Tag)450 },
        { "Harsh Training", (Tag)451 },
        { "Hated Protagonist", (Tag)452 },
        { "Healers", (Tag)453 },
        { "Healing", (Tag)942 },
        { "Heartwarming", (Tag)454 },
        { "Heaven", (Tag)455 },
        { "Heavenly Tribulation", (Tag)456 },
        { "Hell", (Tag)457 },
        { "Helpful Protagonist", (Tag)458 },
        { "Herbalist", (Tag)459 },
        { "Heroes", (Tag)460 },
        { "Heterochromia", (Tag)461 },
        { "Hidden Abilities", (Tag)462 },
        { "Hiding True Abilities", (Tag)463 },
        { "Hiding True Identity", (Tag)464 },
        { "Hikikomori", (Tag)465 },
        { "Homunculus", (Tag)466 },
        { "Honest Protagonist", (Tag)467 },
        { "Hospital", (Tag)468 },
        { "Hot-blooded Protagonist", (Tag)469 },
        { "Human Experimentation", (Tag)470 },
        { "Human Weapon", (Tag)471 },
        { "Human-Nonhuman Relationship", (Tag)472 },
        { "Humanoid Protagonist", (Tag)473 },
        { "Hunters", (Tag)474 },
        { "Hypnotism", (Tag)475 },
        { "Identity Crisis", (Tag)476 },
        { "Imaginary Friend", (Tag)477 },
        { "Immortals", (Tag)478 },
        { "Imperial Harem", (Tag)479 },
        { "Incest", (Tag)480 },
        { "Incubus", (Tag)481 },
        { "Indecisive Protagonist", (Tag)482 },
        { "Industrialization", (Tag)483 },
        { "Inferiority Complex", (Tag)484 },
        { "Inheritance", (Tag)485 },
        { "Inscriptions", (Tag)486 },
        { "Insects", (Tag)487 },
        { "Interconnected Storylines", (Tag)488 },
        { "Interdimensional Travel", (Tag)489 },
        { "Introverted Protagonist", (Tag)490 },
        { "Investigations", (Tag)491 },
        { "Invisibility", (Tag)492 },
        { "Jack of All Trades", (Tag)493 },
        { "Jealousy", (Tag)494 },
        { "Jiangshi", (Tag)495 },
        { "Jobless Class", (Tag)496 },
        { "Kidnappings", (Tag)498 },
        { "Kind Love Interests", (Tag)499 },
        { "Kingdom Building", (Tag)500 },
        { "Kingdoms", (Tag)501 },
        { "Knights", (Tag)502 },
        { "Kuudere", (Tag)503 },
        { "Lack of Common Sense", (Tag)504 },
        { "Language Barrier", (Tag)505 },
        { "Late Romance", (Tag)506 },
        { "Lawyers", (Tag)507 },
        { "Lazy Protagonist", (Tag)508 },
        { "Leadership", (Tag)509 },
        { "Legends", (Tag)510 },
        { "Level System", (Tag)511 },
        { "Library", (Tag)512 },
        { "Limited Lifespan", (Tag)513 },
        { "Living Abroad", (Tag)514 },
        { "Living Alone", (Tag)515 },
        { "Loli", (Tag)516 },
        { "Loneliness", (Tag)517 },
        { "Loner Protagonist", (Tag)518 },
        { "Long Separations", (Tag)519 },
        { "Long-distance Relationship", (Tag)520 },
        { "Lost Civilizations", (Tag)521 },
        { "Lottery", (Tag)522 },
        { "Love at First Sight", (Tag)523 },
        { "Love Interest Falls in Love First", (Tag)524 },
        { "Love Rivals", (Tag)525 },
        { "Love Triangles", (Tag)526 },
        { "Lovers Reunited", (Tag)527 },
        { "Low-key Protagonist", (Tag)528 },
        { "Loyal Subordinates", (Tag)529 },
        { "Lucky Protagonist", (Tag)530 },
        { "Magic", (Tag)531 },
        { "Magic Beasts", (Tag)532 },
        { "Magic Formations", (Tag)533 },
        { "Magical Girls", (Tag)534 },
        { "Magical Space", (Tag)535 },
        { "Magical Technology", (Tag)536 },
        { "Maids", (Tag)537 },
        { "Male Protagonist", (Tag)538 },
        { "Male to Female", (Tag)539 },
        { "Male Yandere", (Tag)540 },
        { "Management", (Tag)541 },
        { "Mangaka", (Tag)542 },
        { "Manipulative Characters", (Tag)543 },
        { "Manly Gay Couple", (Tag)544 },
        { "Marriage", (Tag)545 },
        { "Marriage of Convenience", (Tag)546 },
        { "Martial Spirits", (Tag)547 },
        { "Masochistic Characters", (Tag)548 },
        { "Master-Disciple Relationship", (Tag)549 },
        { "Master-Servant Relationship", (Tag)550 },
        { "Masturbation", (Tag)551 },
        { "Matriarchy", (Tag)552 },
        { "Mature Protagonist", (Tag)553 },
        { "Medical Knowledge", (Tag)554 },
        { "Medieval", (Tag)555 },
        { "Mercenaries", (Tag)556 },
        { "Merchants", (Tag)557 },
        { "Military", (Tag)558 },
        { "Mind Break", (Tag)559 },
        { "Mind Control", (Tag)560 },
        { "Misandry", (Tag)561 },
        { "Mismatched Couple", (Tag)562 },
        { "Misunderstandings", (Tag)563 },
        { "MMORPG", (Tag)564 },
        { "Mob Protagonist", (Tag)565 },
        { "Models", (Tag)566 },
        { "Modern Day", (Tag)567 },
        { "Modern Fantasy", (Tag)1268 },
        { "Modern Knowledge", (Tag)568 },
        { "Modern Time", (Tag)1536 },
        { "Money Grubber", (Tag)569 },
        { "Monster Girls", (Tag)570 },
        { "Monster Society", (Tag)571 },
        { "Monster Tamer", (Tag)572 },
        { "Monsters", (Tag)573 },
        { "Movies", (Tag)574 },
        { "Mpreg", (Tag)575 },
        { "Multiple Identities", (Tag)576 },
        { "Multiple Personalities", (Tag)577 },
        { "Multiple POV", (Tag)578 },
        { "Multiple Protagonists", (Tag)579 },
        { "Multiple Realms", (Tag)580 },
        { "Multiple Reincarnated Individuals", (Tag)581 },
        { "Multiple Timelines", (Tag)582 },
        { "Multiple Transported Individuals", (Tag)583 },
        { "Murders", (Tag)584 },
        { "Music", (Tag)585 },
        { "Mutated Creatures", (Tag)586 },
        { "Mutations", (Tag)587 },
        { "Mute Character", (Tag)588 },
        { "Mysterious Family Background", (Tag)589 },
        { "Mysterious Illness", (Tag)590 },
        { "Mysterious Past", (Tag)591 },
        { "Mystery Solving", (Tag)592 },
        { "Mythical Beasts", (Tag)593 },
        { "Mythology", (Tag)594 },
        { "Naive Protagonist", (Tag)595 },
        { "Narcissistic Protagonist", (Tag)596 },
        { "Nationalism", (Tag)597 },
        { "Near-Death Experience", (Tag)598 },
        { "Necromancer", (Tag)599 },
        { "Neet", (Tag)600 },
        { "Netorare", (Tag)601 },
        { "Netorase", (Tag)602 },
        { "Netori", (Tag)603 },
        { "Nightmares", (Tag)604 },
        { "Ninjas", (Tag)605 },
        { "Nobles", (Tag)606 },
        { "Non-human Protagonist", (Tag)1428 },
        { "Non-humanoid Protagonist", (Tag)607 },
        { "Non-linear Storytelling", (Tag)608 },
        { "Nudity", (Tag)609 },
        { "Nurses", (Tag)610 },
        { "Obsessive Love", (Tag)611 },
        { "Office Romance", (Tag)612 },
        { "Older Love Interests", (Tag)613 },
        { "Omegaverse", (Tag)614 },
        { "Oneshot", (Tag)615 },
        { "Online Romance", (Tag)616 },
        { "Onmyouji", (Tag)617 },
        { "Orcs", (Tag)618 },
        { "Organized Crime", (Tag)619 },
        { "Orphans", (Tag)621 },
        { "Otaku", (Tag)622 },
        { "Otome Game", (Tag)623 },
        { "Outcasts", (Tag)624 },
        { "Outdoor Intercourse", (Tag)625 },
        { "Outer Space", (Tag)626 },
        { "Overpowered Protagonist", (Tag)627 },
        { "Overprotective Siblings", (Tag)628 },
        { "Pacifist Protagonist", (Tag)629 },
        { "Paizuri", (Tag)630 },
        { "Pansexual Protagonist", (Tag)1037 },
        { "Parallel Worlds", (Tag)631 },
        { "Parasites", (Tag)632 },
        { "Parent Complex", (Tag)633 },
        { "Parody", (Tag)634 },
        { "Part-Time Job", (Tag)635 },
        { "Past Plays a Big Role", (Tag)636 },
        { "Past Trauma", (Tag)637 },
        { "Persistent Love Interests", (Tag)638 },
        { "Personality Changes", (Tag)639 },
        { "Perverted Protagonist", (Tag)640 },
        { "Pets", (Tag)641 },
        { "Pharmacist", (Tag)642 },
        { "Philosophical", (Tag)643 },
        { "Phobias", (Tag)644 },
        { "Phoenixes", (Tag)645 },
        { "Photography", (Tag)646 },
        { "Pill Based Cultivation", (Tag)647 },
        { "Pill Concocting", (Tag)648 },
        { "Pilots", (Tag)649 },
        { "Pirates", (Tag)650 },
        { "Playboys", (Tag)651 },
        { "Playful Protagonist", (Tag)652 },
        { "Poetry", (Tag)653 },
        { "Poisons", (Tag)654 },
        { "Police", (Tag)655 },
        { "Polite Protagonist", (Tag)656 },
        { "Politics", (Tag)657 },
        { "Polyandry", (Tag)658 },
        { "Polygamy", (Tag)659 },
        { "Poor Protagonist", (Tag)660 },
        { "Poor to Rich", (Tag)661 },
        { "Popular Love Interests", (Tag)662 },
        { "Possession", (Tag)663 },
        { "Possessive Characters", (Tag)664 },
        { "Post-apocalyptic", (Tag)665 },
        { "Power Couple", (Tag)666 },
        { "Power Struggle", (Tag)667 },
        { "Pragmatic Protagonist", (Tag)668 },
        { "Precognition", (Tag)669 },
        { "Pregnancy", (Tag)670 },
        { "Pretend Lovers", (Tag)671 },
        { "Previous Life Talent", (Tag)672 },
        { "Priestesses", (Tag)673 },
        { "Priests", (Tag)674 },
        { "Prison", (Tag)675 },
        { "Proactive Protagonist", (Tag)676 },
        { "Programmer", (Tag)677 },
        { "Prophecies", (Tag)678 },
        { "Prostitutes", (Tag)679 },
        { "Protagonist Falls in Love First", (Tag)680 },
        { "Protagonist Loyal to Love Interest", (Tag)681 },
        { "Protagonist Strong from the Start", (Tag)682 },
        { "Protagonist with Multiple Bodies", (Tag)683 },
        { "Psychic Powers", (Tag)684 },
        { "Psychopaths", (Tag)685 },
        { "Puppeteers", (Tag)686 },
        { "Quiet Characters", (Tag)687 },
        { "Quirky Characters", (Tag)688 },
        { "R-15", (Tag)689 },
        { "R-18", (Tag)690 },
        { "Race Change", (Tag)691 },
        { "Racism", (Tag)692 },
        { "Rape", (Tag)693 },
        { "Rebellion", (Tag)695 },
        { "Reincarnated as a Monster", (Tag)696 },
        { "Reincarnated as an Object", (Tag)697 },
        { "Reincarnated into a Game World", (Tag)698 },
        { "Reincarnated into Another World", (Tag)699 },
        { "Reincarnation", (Tag)700 },
        { "Religions", (Tag)701 },
        { "Reluctant Protagonist", (Tag)702 },
        { "Reporters", (Tag)703 },
        { "Restaurant", (Tag)704 },
        { "Resurrection", (Tag)705 },
        { "Returning from Another World", (Tag)706 },
        { "Revenge", (Tag)707 },
        { "Reverse Harem", (Tag)708 },
        { "Reverse Rape", (Tag)709 },
        { "Rich to Poor", (Tag)710 },
        { "Righteous Protagonist", (Tag)711 },
        { "Rivalry", (Tag)712 },
        { "Romantic Subplot", (Tag)713 },
        { "Roommates", (Tag)714 },
        { "Royalty", (Tag)715 },
        { "RPG", (Tag)1089 },
        { "Ruthless Protagonist", (Tag)716 },
        { "Sadistic Characters", (Tag)717 },
        { "Saints", (Tag)718 },
        { "Salaryman", (Tag)719 },
        { "Samurai", (Tag)720 },
        { "Satire", (Tag)1976 },
        { "Saving the World", (Tag)721 },
        { "Scheming", (Tag)722 },
        { "Schizophrenia", (Tag)723 },
        { "Scientists", (Tag)724 },
        { "Sculptors", (Tag)725 },
        { "Sealed Power", (Tag)726 },
        { "Second Chance", (Tag)727 },
        { "Secret Crush", (Tag)728 },
        { "Secret Identity", (Tag)729 },
        { "Secret Organizations", (Tag)730 },
        { "Secret Relationship", (Tag)731 },
        { "Secretive Protagonist", (Tag)732 },
        { "Secrets", (Tag)733 },
        { "Sect Development", (Tag)734 },
        { "Seduction", (Tag)735 },
        { "Seeing Things Other Humans Can't", (Tag)736 },
        { "Selfish Protagonist", (Tag)737 },
        { "Selfless Protagonist", (Tag)738 },
        { "Seme Protagonist", (Tag)739 },
        { "Senpai-Kouhai Relationship", (Tag)740 },
        { "Sentient Objects", (Tag)741 },
        { "Sentimental Protagonist", (Tag)742 },
        { "Serial Killers", (Tag)743 },
        { "Servants", (Tag)744 },
        { "Seven Deadly Sins", (Tag)745 },
        { "Seven Virtues", (Tag)746 },
        { "Sex Friends", (Tag)747 },
        { "Sexual Abuse", (Tag)749 },
        { "Sexual Cultivation Technique", (Tag)750 },
        { "Shameless Protagonist", (Tag)751 },
        { "Shapeshifters", (Tag)752 },
        { "Sharing A Body", (Tag)753 },
        { "Sharp-tongued Characters", (Tag)754 },
        { "Shield User", (Tag)755 },
        { "Shikigami", (Tag)756 },
        { "Short Story", (Tag)757 },
        { "Shota", (Tag)758 },
        { "Showbiz", (Tag)761 },
        { "Shy Characters", (Tag)762 },
        { "Sibling Rivalry", (Tag)763 },
        { "Siblings", (Tag)765 },
        { "Siblings Care", (Tag)764 },
        { "Siblings Not Related by Blood", (Tag)766 },
        { "Sickly Characters", (Tag)767 },
        { "Sign Language", (Tag)768 },
        { "Singers", (Tag)769 },
        { "Single Parent", (Tag)770 },
        { "Sister Complex", (Tag)771 },
        { "Skill Assimilation", (Tag)772 },
        { "Skill Books", (Tag)773 },
        { "Skill Creation", (Tag)774 },
        { "Slave Harem", (Tag)775 },
        { "Slave Protagonist", (Tag)776 },
        { "Slaves", (Tag)777 },
        { "Sleeping", (Tag)778 },
        { "Slow Growth at Start", (Tag)779 },
        { "Slow Romance", (Tag)780 },
        { "Smart Couple", (Tag)781 },
        { "Social Outcasts", (Tag)782 },
        { "Soldiers", (Tag)783 },
        { "Soul Power", (Tag)784 },
        { "Souls", (Tag)785 },
        { "Spatial Manipulation", (Tag)786 },
        { "Spear Wielder", (Tag)787 },
        { "Special Abilities", (Tag)788 },
        { "Special Forces", (Tag)497 },
        { "Spies", (Tag)789 },
        { "Spirit Advisor", (Tag)790 },
        { "Spirit Users", (Tag)791 },
        { "Spirits", (Tag)792 },
        { "Stalkers", (Tag)793 },
        { "Stockholm Syndrome", (Tag)794 },
        { "Stoic Characters", (Tag)795 },
        { "Store Owner", (Tag)796 },
        { "Straight Seme", (Tag)797 },
        { "Straight Uke", (Tag)798 },
        { "Strategic Battles", (Tag)799 },
        { "Strategist", (Tag)800 },
        { "Strength-based Social Hierarchy", (Tag)801 },
        { "Strong Love Interests", (Tag)802 },
        { "Strong to Stronger", (Tag)803 },
        { "Stubborn Protagonist", (Tag)804 },
        { "Student Council", (Tag)805 },
        { "Student-Teacher Relationship", (Tag)806 },
        { "Subtle Romance", (Tag)807 },
        { "Succubus", (Tag)808 },
        { "Sudden Strength Gain", (Tag)809 },
        { "Sudden Wealth", (Tag)810 },
        { "Suicides", (Tag)811 },
        { "Summoned Hero", (Tag)812 },
        { "Summoning Magic", (Tag)813 },
        { "Superheroes", (Tag)44746 },
        { "Survival", (Tag)814 },
        { "Survival Game", (Tag)815 },
        { "Sword And Magic", (Tag)816 },
        { "Sword Wielder", (Tag)817 },
        { "System Administrator", (Tag)818 },
        { "Teachers", (Tag)819 },
        { "Teamwork", (Tag)820 },
        { "Technological Gap", (Tag)821 },
        { "Tentacles", (Tag)822 },
        { "Terminal Illness", (Tag)823 },
        { "Terrorists", (Tag)824 },
        { "Thieves", (Tag)825 },
        { "Threesome", (Tag)826 },
        { "Thriller", (Tag)827 },
        { "Time Loop", (Tag)828 },
        { "Time Manipulation", (Tag)829 },
        { "Time Paradox", (Tag)830 },
        { "Time Skip", (Tag)831 },
        { "Time Travel", (Tag)832 },
        { "Timid Protagonist", (Tag)833 },
        { "Tomboyish Female Lead", (Tag)834 },
        { "Torture", (Tag)835 },
        { "Toys", (Tag)836 },
        { "Tragic Past", (Tag)837 },
        { "Transformation Ability", (Tag)838 },
        { "Transgender", (Tag)1088 },
        { "Transmigration", (Tag)839 },
        { "Transplanted Memories", (Tag)840 },
        { "Transported into a Game World", (Tag)841 },
        { "Transported into Another World", (Tag)842 },
        { "Transported Modern Structure", (Tag)843 },
        { "Trap", (Tag)844 },
        { "Tribal Society", (Tag)845 },
        { "Trickster", (Tag)846 },
        { "Trolls", (Tag)1071 },
        { "Tsundere", (Tag)847 },
        { "Twins", (Tag)848 },
        { "Twisted Personality", (Tag)849 },
        { "Ugly Protagonist", (Tag)850 },
        { "Ugly to Beautiful", (Tag)851 },
        { "Unconditional Love", (Tag)852 },
        { "Underestimated Protagonist", (Tag)853 },
        { "Unique Cultivation Technique", (Tag)854 },
        { "Unique Weapon User", (Tag)855 },
        { "Unique Weapons", (Tag)856 },
        { "Unlucky Protagonist", (Tag)857 },
        { "Unreliable Narrator", (Tag)858 },
        { "Unrequited Love", (Tag)859 },
        { "Valkyries", (Tag)860 },
        { "Vampires", (Tag)861 },
        { "Villainess Noble Girls", (Tag)862 },
        { "Virtual Reality", (Tag)863 },
        { "Vocaloid", (Tag)864 },
        { "Voice Actors", (Tag)865 },
        { "Voyeurism", (Tag)866 },
        { "Waiters", (Tag)867 },
        { "War Records", (Tag)868 },
        { "Wars", (Tag)869 },
        { "Weak Protagonist", (Tag)870 },
        { "Weak to Strong", (Tag)871 },
        { "Wealthy Characters", (Tag)872 },
        { "Werebeasts", (Tag)873 },
        { "Wishes", (Tag)874 },
        { "Witches", (Tag)875 },
        { "Wizards", (Tag)876 },
        { "World Hopping", (Tag)877 },
        { "World Invasion", (Tag)1036 },
        { "World Travel", (Tag)878 },
        { "World Tree", (Tag)879 },
        { "Writers", (Tag)880 },
        { "Wuxia", (Tag)1143 },
        { "Xianxia", (Tag)1142 },
        { "Xuanhuan", (Tag)1141 },
        { "Yandere", (Tag)881 },
        { "Youkai", (Tag)882 },
        { "Younger Brothers", (Tag)883 },
        { "Younger Love Interests", (Tag)884 },
        { "Younger Sisters", (Tag)885 },
        { "Zombies", (Tag)886 },
    });
}